#! /usr/bin/env python
# encoding: utf-8

import os
from waflib import Utils

top = '.'

# Kept in step with the subprojects the top-level wscript drops for a Rust
# build, which it does on macOS alone.
RUST_MODULES = ['scenefilecache', 'soundemittersystem']

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	target_dir = bld.bldnode.make_node('cargo-target')
	profile_dir = target_dir.make_node('release')

	if bld.env.DEST_OS == 'darwin':
		dynamic_pattern = 'lib%s.dylib'
	elif bld.env.DEST_OS == 'win32':
		dynamic_pattern = '%s.dll'
	else:
		dynamic_pattern = 'lib%s.so'

	abi = profile_dir.make_node(dynamic_pattern % 'source_abi')
	# Engine modules that are Rust alone. Each takes the file name of the C++
	# module it replaces, which the top-level wscript leaves out of the build.
	modules = []
	if bld.env.DEST_OS == 'darwin':
		modules = [profile_dir.make_node(dynamic_pattern % name) for name in RUST_MODULES]
	launcher = None

	outputs = [abi] + modules
	if bld.env.DEST_OS != 'win32':
		outputs.append(profile_dir.make_node('libsource_abi.a'))
	if bld.env.DEST_OS == 'darwin':
		launcher = profile_dir.make_node('source-launcher')
		outputs.append(launcher)

	sources = bld.path.ant_glob('**/*.rs **/Cargo.toml')
	sources.append(bld.srcnode.find_node('Cargo.toml'))
	lock = bld.srcnode.find_node('Cargo.lock')
	if lock:
		sources.append(lock)

	def run_cargo(task):
		cargo = task.env.CARGO[0]
		return task.exec_command([
			cargo,
			'build',
			'--workspace',
			'--release',
			'--target-dir', target_dir.abspath(),
		], cwd=bld.srcnode.abspath())

	bld(
		name = 'rust_engine_workspace',
		rule = run_cargo,
		source = sources,
		target = outputs,
		always = False,
	)
	bld.install_files(bld.env.LIBDIR, [abi] + modules, chmod=Utils.O755)
	if launcher:
		bld.install_as(os.path.join(bld.env.BINDIR, 'hl2_launcher'),
			launcher, chmod=Utils.O755)
